import type { StatsData } from "@/data/schema"

const baseFields = {
  ai_additions: 50,
  ai_deletions: 10,
  human_additions: 30,
  human_deletions: 5,
  ai_model_line_changes: {},
  ai_line_changes_total: 0,
  ai_model_costs: {},
  ai_model_breakdown: [],
  ai_model_total_cost: 0.42,
  ai_input_tokens: 1000,
  ai_output_tokens: 500,
  ai_prompt_length_avg: 100,
  ai_prompt_length_avg_per_session: 50,
  ai_prompt_length_median_per_session: 40,
  ai_prompt_length_sum: 500,
  ai_prompt_events_total: 10,
  ai_prompt_events_avg_per_session: 2,
  ai_prompt_events_median_per_session: 2,
  ai_sessions: 5,
  categories: [],
  projects: [],
  editors: [],
  operating_systems: [],
  dependencies: [],
  machines: [],
  best_day: null,
  status: "ok",
  is_up_to_date: true,
  percent_calculated: 100,
  is_already_updating: false,
  is_stuck: false,
  is_including_today: true,
  is_coding_activity_visible: true,
  is_language_usage_visible: true,
  is_editor_usage_visible: true,
  is_category_usage_visible: true,
  is_os_usage_visible: true,
  writes_only: false,
  holidays: 0,
  days_minus_holidays: 7,
  timeout: 15,
}

export const weekData: StatsData = {
  ...baseFields,
  total_seconds: 14400,
  total_seconds_including_other_language: 14400,
  human_readable_total: "4 hrs",
  human_readable_total_including_other_language: "4 hrs",
  daily_average: 2057,
  daily_average_including_other_language: 2057,
  human_readable_daily_average: "34 mins",
  human_readable_daily_average_including_other_language: "34 mins",
  languages: [
    { name: "TypeScript", total_seconds: 10800, percent: 75, digital: "3:00", text: "3 hrs", hours: 3, minutes: 0, seconds: 10800 },
    { name: "Python", total_seconds: 3600, percent: 25, digital: "1:00", text: "1 hr", hours: 1, minutes: 0, seconds: 3600 },
  ],
  range: "last_7_days",
  human_readable_range: "Last 7 Days",
  start: "2024-01-01T00:00:00Z",
  end: "2024-01-07T23:59:59Z",
  timezone: "UTC",
  days_including_holidays: 7,
  created_at: "2024-01-07T00:00:00Z",
  modified_at: "2024-01-07T00:00:00Z",
  user_id: "u1",
  username: "test-user",
}

export const allData: StatsData = {
  ...weekData,
  total_seconds: 864000,
  total_seconds_including_other_language: 864000,
  human_readable_total: "240 hrs",
  human_readable_total_including_other_language: "240 hrs",
  range: "all_time",
  human_readable_range: "All Time",
  start: "2020-01-01T00:00:00Z",
  end: "2024-01-07T23:59:59Z",
  days_including_holidays: 1461,
}
